version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
    volumes:
      - .:/app
    depends_on:
      - tensorflow-serving
  tensorflow-serving:
    image: tensorflow/serving
    ports:
      - "3000:3000"
    environment:
      MODEL_NAME: default
      MODEL_PATH: /models/default/1
